### ISSUE TITLE
CSV: fixed column order?

### ISSUE THREAD

**Issue by niconoe** [enram/vpts-dp#12]
@peterdesmet: I think we already had a quick chat about it, I'd like to take a decision soon:

- Do we guarantee (to consumers) that the columns in the CSV file come in a given, fixed order.

Advantages:
- simplicity: guarantee that `row[3]` always contains the density (for example)

Disadvantages:
- slight deviation: we're adding a (structural) constraint on top of what Frictionless Tabular Data Packages requires
- feels a bit too rigid, especially when the standard evolves (if consumer code relies on the row order, messy situation if the next version of the standard remove 1 column and add 3 more)

**personal opinion**: I wouldn't guarantee it, which will force the consumers to rely on headers (or metadata) to knows how to read a row, which seems a more clean and robust way to do things. It might add a bit of complexity to consumers, but CSV reading tools generally already provide a solution to this problem (for example with Python, using a `DictReader` object will automatically analyse the header and allows retrieving the density with just `row['dens']`, whatever the column order is)

**Comment by peterdesmet** [comment]
I would say that the **vpts format** defines a number of fields (name + concept), in a certain order.

vpts data packages:
- MUST only use those fields: no new ones or same concepts under different name
- Can have those fields in a different order, but best to follow suggested order for better consumption by humans
- Can have a subselection of those fields, to not unnecessarily introduce empty columns + is not scalable when **vpts format** adds/removes columns

Indeed, csv readers will be able to handle these and binding/merging different data frames is possible in R (by default on column name).

It makes it a bit harder to validate a vpts data package agains the table schema defined in the **vpts repository**, but frictionless-py does offer a `schema_sync` to do just that.

**Comment by niconoe** [comment]
@peterdesmet: thanks, I agree about the first two bullet points.

About the third: no mandatory fields (besides timestamp and height), then? That means that all consumer tools won't be able to just say (in their doc) "xxx can consume vpts data", but rather "xxx can consumer vpts data, the following fields are required: dens, ff, dbz". I don't know how much of a problem it would be, though.

**Comment by peterdesmet** [comment]
Regarding point 3: I indeed forgot to mention that we can have required fields in our **vpts format**. All vpts data packages should have these then. Which ones are required is to be defined (but more than timestamp and height I think).

**Comment by niconoe** [comment]
Perfect, we're in line :)

@adokter, @CeciliaNilsson709 (and others!): any advice on which fields should be reasonably always present? We'll mark those as mandatory in the first iteration of the standard!

**Comment by adokter** [comment]
These are essential:
1. datetime
2. height,
3. ff (speed)
4. dd (direction)
5. dens (density)
6. eta (linear reflectivity)
7. sd_vvp (radial velocity standard deviation)
8. DBZH (total reflectivity factor)

7, 8 could likely be omitted without breaking anything critical (I think - but I would need to test), but it will results in loss of functionality in bioRad (insect filtering, visualization of rain), so I would advise against it. Equivalents for 7,8 are available in cajun as well

**Comment by niconoe** [comment]
Thanks a lot @adokter, that's excellent information.

**Comment by niconoe** [comment]
I just added a table (allowed fields) based on @adokter's answer above: https://github.com/enram/vpts/blob/main/specs/vpts_1_0.md#data-file-bird-profiles

I'd be interested in having reviews on this table (@peterdesmet? @CeciliaNilsson709? @adokter? others?). Remember the context:

The current goals of the standard are: 1) to be as close/compatible to vol2bird as possible, but... 2) we should remove things that are too restrictive/niche/implementation-specific if we already see clearly they'll hinder the standard for the future (for example, conceptually incompatible with cajun) 3) it's also the right time for small improvements that are not too risky/complicated (for example, I already replaced the date-time columns by a single datetime as ISO8601)

Some important questions are:

- Is the current selection of fields in the table reasonable?
- Are the "required" fields the right one
- Can someone complete/improve the field descriptions and data types
- Is the current field order meaningful and user-friendly (for a user having a quick glance at the CSV file?) (I currently structured it so all required fields come first, to keep all data files relatively similar)
- are the field names "good"? Is there a reason why DBZH is all uppercase while the others are not?

Thanks a lot!

**Comment by CeciliaNilsson709** [comment]
Looks good! I think @adokter is maybe the best to say if the fields are reasonable also with respect to cajun etc, and what should be required. 

Here are some suggested changes to two descriptions: 
Name | Description
-------|-------
ff | Horizontal speed, m/s
dd | Direction, degrees

and suggestions for those that currently lack:

Name | Description
-------|-------
u | Speed component west to east, m/s
v | Speed component north to south, m/s
gap | Angular data gap detected in T/F
dbz | Animal reflectivity factor, dBZ
w | Vertical speed, m/s
n | Number of data points used for the speed estimates
n_all | Number of data points used for sd_vvp
n_dbz | Number of data points used for reflectivity-based estimates
n_dbz_all | Number of data points used for DBZH

Based on the descriptions in: [vp data definitions](https://adriaandokter.com/bioRad/reference/summary.vp.html) 

* @adokter should dbz also be a required field?
* Note that the definition of "eta" differs in the table and in the vp data definitions. Do we want to define it as biological?
* Not sure about including vertical speed, w. Not really used as far as I know?
* I suggest moving "dens" up so it's the first field after time and height, as it is really the main output variable.
* "dd" is currently included twice.
* Yes, DBZH is written in uppercase according to the metrological standards (to separate it from dbz I think 🤷‍♀️ ).

**Comment by niconoe** [comment]
Thanks a lot @CeciliaNilsson709, that's very helpful. I already updated the table based on your input, I'd be happy to read the others for the remaining questions (required dbz, eta definition, need of vertical speed)

**Comment by adokter** [comment]
Hi all,

The most up-to-date description of the profile quantities can be found here. They are almost the same as above, but with a little more explanation and being explicit about the units:
https://adriaandokter.com/bioRad/dev/reference/summary.vp.html#details

* dbz is not required, is it can be calculated from eta and the radar wavelength, which should be a required attribute
* speed: for both ff,u,v I would mention this is *ground* speed. Fixing this also in bioRad documentation https://github.com/adokter/bioRad/pull/462
* vertical speed: I would include it since we have it, and for consistency.

**Comment by niconoe** [comment]
Thanks all for the valuable input. I *think* I've correctly compiled all the info above in the spec (table schema). I'll ask a more  exhaustive review soon, but in the meantime I'll close this issue that is becoming a bit too big and broad for my taste :)
