### ISSUE TITLE
Define good name and abbreviation

### ISSUE THREAD

**Issue by niconoe** [enram/vpts-dp#13]
The current introduction on README is:

`vpts is a community developed data exchange format for time series of vertical profiles (vpts)`

Shouldn't we restrict this standard to birds (or maybe other animals), and reflect that in the documentation, or is it better to keep it open to more usages?

Opinions welcome :)

**Comment by peterdesmet** [comment]
Good point, I think we need a better name and abbreviation actually. I suggest:

> **VPTS-DP** is a **data exchange format for biological signals detected by weather radars**. VPTS data are time series of vertical profiles of biological signals. These ...
