### ISSUE TITLE
Validation of data

### ISSUE THREAD

**Issue by niconoe** [enram/vpts-dp#14]
AFAIK, there should be at least:

- A machine-readable profile allowing the validation of `datapackage.json`
- A machine-readable profile for the CSV data table (mandatory fields, ...)

For automatic validation, we might need custom tools if all the checks needed* are not available in the standard frictionless tooling - to be investigated)

*: I'm thinking of the guaranteed row order, for example.

**Comment by peterdesmet** [comment]
Nico, can you describe what you want to test exactly? I suggest:
- profile is valid json
- table schema is valid json
- an example vpts data package is valid against the specs

**Comment by niconoe** [comment]
In practice, I'd love to have one single command that checks as many things as possible to ensure a given package is compliant.

I guess the frictionless-py tools already provide most of it:

- ability to check datapackage is not only valid JSON, but also conforms to our specifications (required metadata, ...)
- ability to check the table schema conforms to our specs

I haven't checked yet, but there might be points in our specs that can't be checked yet with the existing tools (for example the data row order - by datetime then altitude).

We might therefore implement a simple tool (`vpts_validate` under the `vpts_tools` repo?) that would be a thin wrapper around the existing validation tools, but also adding:
   - out custom checks
   - the ability to perform all checks with a single command

**Comment by peterdesmet** [comment]
I would start with the default

    frictionless validate datapackage.json

It does many things already

**Comment by peterdesmet** [comment]
@niconoe picking this up again, but this issue might need to be moved to vptstools.

Validation can rely on frictionless, unless we create our own definition for what is a required field (#26). Below I'm using package level validation, but I'm pretty sure you can do resource level validation as well. You'd have to use the `--schema-sync` option, because our specs state that not all fields have to be included.

## Valid example

1. [example_vpts.csv](https://github.com/enram/vpts/files/8639124/example_vpts.csv) (created as in #25)
2. A datapackage.json:

```json
{
  "name": "vpts",
  "path": "example_vpts.csv",
  "profile": "tabular-data-resource",
  "format": "csv",
  "mediatype": "text/csv",
  "encoding": "utf-8",
  "dialect": "https://raw.githubusercontent.com/frictionlessdata/frictionless-r/main/tests/testthat/data/dialect.json",
  "schema": "https://raw.githubusercontent.com/enram/vpts/main/vpts-table-schema.json"
}
```

Validates with:

```
frictionless validate datapackage.json --schema-sync
```

**Comment by peterdesmet** [comment]
Validation is possible using Frictionless framework:

1. Download a vpts csv file, e.g. https://aloft.s3-eu-west-1.amazonaws.com/baltrad/daily/bejab/2023/bejab_vpts_20230311.csv
2. Next to the local csv file, create a file like this `vpts-resource.json`:

```json
{
  "name": "bejab_vpts_20230311",
  "type": "table",
  "path": "bejab_vpts_20230311.csv",
  "scheme": "file",
  "format": "csv",
  "mediatype": "text/csv",
  "encoding": "utf-8",
  "schema": "https://raw.githubusercontent.com/enram/vpts-csv/v1.0/vpts-csv-table-schema.json"
}
```

3. Validate with `frictionless validate vpts-resource.json`.

There are ways to optimize this. vptstools offers a `validate_vpts()` function: https://github.com/enram/vptstools/blob/bfb2c7f57bdf85c3fdf1666709f4c48c2086cb8e/src/vptstools/vpts.py#L281-L301
