### ISSUE TITLE
Remove duplicate table schema

### ISSUE THREAD

**Issue by niconoe** [enram/vpts-dp#17]
- The table schema should appear in `_data/vps-table-schema.json`
- There's currently another (more rich, but outdated) table schema definition (in `table-schemas/vpts.json`). 

TODO: 
- Move all table definition to  `_data/vps-table-schema.json`
- Also remove `table-schmas/vol2bird.json` since a distinct vol2bird schema doesn't make sense

**Comment by niconoe** [comment]
Done

**Comment by peterdesmet** [comment]
Best would to have it in the root.

**Comment by peterdesmet** [comment]
This one is the normative one: https://github.com/enram/vpts-dp/blob/main/vpts-table-schema.json Rest should be removed

**Comment by niconoe** [comment]
I think we're good, can't find any duplicated/outdated table schema data in the repository. @peterdesmet : are the [two symlinks in _data](https://github.com/enram/vpts-dp/tree/main/_data) necessary for the Jekyll website?

**Comment by peterdesmet** [comment]
Yes, they are, since Jekyll only reads data files (csv, json, etc.) from `_data`.
