### ISSUE TITLE
Different GitHub README than site home page

### ISSUE THREAD

**Issue by niconoe** [enram/vpts-dp#19]
Currently, the same `README.md` is used as a source for two different web pages. It would be great if:

- The GitHub repository home page had only a very short paragraph redirecting visitors to the [the exchange format website](https://enram.github.io/vpts-dp/)
- [the website homepage](https://enram.github.io/vpts-dp/) continues to show the current README.md content (introduction to the project and format)

**Comment by peterdesmet** [comment]
I think it's fine if the two are the same? If you don't want this, we can add an `index.md`, but then we have to maintain two files.

**Comment by niconoe** [comment]
Yeah, I'd prefer to have two files despite the small maintenance overhear, because I think it's not immediately obvious when you end up on the GitHub page that if you just want to read about the format, you should go to the website rather than trying to extract the info from the raw files in the repository.

So if I understood correctly, I can just add an `index.md` file and it will be picked up by Jekyll for the home page instead of README.md?

**Comment by peterdesmet** [comment]
I think so. You can the also remove the frontmatter from README (and put it in index.md)

**Comment by niconoe** [comment]
Done!
