### ISSUE TITLE
Provide (field) examples in `vpts_table_schema.json`

### ISSUE THREAD

**Issue by niconoe** [enram/vpts-dp#20]
They'll then appear on the website table.

If I interpret the table schema specs correctly, arbitrary extra properties in the field descriptor (such as "example" here) are allowed.

**Comment by peterdesmet** [comment]
Yes, I would include `example` as extra property, e.g. https://github.com/tdwg/camtrap-dp/blob/main/deployments-table-schema.json#L31

**Comment by niconoe** [comment]
Done
