### ISSUE TITLE
Clarifications about Data Package properties (metadata)

### ISSUE THREAD

**Issue by niconoe** [enram/vpts-dp#21]
Hey @peterdesmet, I noticed the following sentence on the [metadata documentation page](https://enram.github.io/vpts-dp/metadata/):

> It follows the Tabular Data Package specifications and **includes default Data Package properties** and specific VPTS-DP properties 

There are also a few of those properties listed: `name`, `id`, `created`, `profile`, `sources`, `contributors`, `resources`.

If I'm not mistaken, the Data Package specs only requires the `resources` property, so I was wondering what we should do for v1, and what you wanted to express on that page. Do we want to enforce that a `vpts-dp` always provides `name`, `id`, `created`, `profile`, `sources`, `contributors` attributes (in addition to`resources` which is already required for all data packages, and our specific properties such as `radar`)?

Thanks a lot!

**Comment by peterdesmet** [comment]
The ones that are listed are probably a copy/paste from https://tdwg.github.io/camtrap-dp/metadata/ but only to provide a table of contents.

To really make the required, this needs to be added to vpts-dp-profile.json (see again how this is done in Camtrap DP). Regarding which ones: I need to review this, but I’m thinking `created` and  `radar`. `resources` is already required indeed.

**Comment by peterdesmet** [comment]
Will not implement this, in favour of a simple flat format as described in #25.
