### ISSUE TITLE
Required fields in VPTS

### ISSUE THREAD

**Issue by peterdesmet** [enram/vpts-dp#26]
We have previously identified a number of fields in VPTS that are required (i.e. cannot be empty). For some of those however the `example_vpts` has `NaN` values (expressed as empty in the CSV), so I'm wondering if we should not loosen the requirements:

- [x] `radar`: required, always present
- [x] `datetime`: required, always present
- [x] `height`: required, always present
- [ ] `u`: not required, sometimes `NaN` 
- [ ] `v`: not required, sometimes `NaN` 
- [ ] `w`: not required, sometimes `NaN` 
- [x] `ff`: required, but sometimes `NaN`
- [x] `dd`: required, but sometimes `NaN`
- [x] `sd_vvp`: required, but sometimes `NaN`
- [ ] `gap`: not required, likely always present
- [x] `eta`: required, but sometimes `NaN`
- [ ] `dens`: required, but sometimes `NaN`
- [ ] `dbz`: not required, sometimes `NaN`
- [ ] `dbz_all` (`DBZH`): required, sometimes `NaN`
- [ ] `n`: not required, likely always present
- [ ] `n_dbz`: not required, likely always present
- [ ] `n_all`: not required, likely always present
- [ ] `n_dbz_all`: not required, likely always present
- [ ] `rcs`: make required? likely always present
- [ ] `sd_vvp_threshold`: make required? likely always present
- [ ] `vcp`: make not required? sometimes `NA_real_`
- [x] `radar_lon`: make required? 
- [x] `radar_lat`: make required?
- [x] `radar_height`: make required?
- [x] `radar_wavelength`: make required?

**Comment by adokter** [comment]
I've marked the ones I think should be required, mostly repeating our earlier assignment (the fact that certain values are often `NaN` is more a reflection of the fact that certain values cannot be determined when there is low signal, not that they are optional)

* `sd_vvp_threshold` and `rcs` can be set afterwards, so no need to make them required.
* `radar_height`: we have to be really clear about what this means, I suggest taking the antenna height, so the height of the  center of the antenna dish.

**Comment by adokter** [comment]
The pair `ff`,`dd` could be exchanged with `u`,`v`, they contain the same information and are therefore interchangeable. But `ff`,`dd` is a little easier to interpret if you scan through the raw data imo.

**Comment by peterdesmet** [comment]
Ok, the fields you requested have been set as required in 49528a1.

radar_height is defined as:

> Height of the center of the radar antenna in m above sea level.

So I think that is fine.
