### ISSUE TITLE
Min/max values

### ISSUE THREAD

**Issue by peterdesmet** [enram/vpts-dp#27]
We have defined minimum (and sometimes maximum) values for fields (see https://enram.github.io/vpts/format/), but not all. Can the following be reviewed (check those that are ok, reply below if not), **knowing that fields that can contain `NaN` should not have min/max values defined,** because they will fail for those values.

- [x] `height` min: -200 m above sea level
- [x] `height` max: 25000 m above sea level
- [x] `u` min: -100 m/s
- [x] `u` max: 100 m/s
- [x] `v` min: -100 m/s
- [x] `v` max:  100 m/s
- [x] `w` min: undefined m/s
- [x] `w` max: undefined m/s
- [x] `ff` min: 0 m/s
- [x] `ff` max: 100 m/s
- [x] `dd` min: 0 degrees
- [x] `dd` max: 360 degrees
- [x] `sd_vvp` min: 0 m/s
- [x] `sd_vvp` max: 100 m/s
- [x] `eta` min: 0 cm^2/km^3
- [x] `eta` max: Inf cm^2/km^3
- [x] `dens` min: 0 animals/km^3
- [x] `dens` max: Inf animals/km^3
- [x] `dbz` min: -Inf dBZ
- [x] `dbz` max: 100 dBZ
- [x] `dbz_all` min: -Inf dBZ
- [x] `dbz_all` max: 100 dBZ
- [x] `n` min: 0
- [x] `n` max: undefined
- [x] `n_dbz` min: 0
- [x] `n_dbz` max: undefined
- [x] `n_all` min: 0
- [x] `n_all` max: undefined
- [x] `n_dbz_all` min: 0
- [x] `n_dbz_all` max: undefined
- [x] `rcs` min: 0.01 cm^2 **Anything larger than zero**
- [x] `rcs` max: Inf cm^2
- [x] `sd_vvp_threshold` min: 0 m/s
- [x] `sd_vvp_threshold` max: 100 m/s
- [x] `vcp` enum: [12, 212, 112, 215, 121, 31, 32, 35]
- [x] `radar_lon` min: -180 degrees
- [x] `radar_lon` max: 180 degrees
- [x] `radar_lat` min: -90 degrees
- [x] `radar_lat` max: 90 degrees
- [x] `radar_height` min: -200 m above sea level
- [x] `radar_height` max: 9000 m above sea level
- [x] `radar_wavelength` min: 0.1 cm
- [x] `radar_wavelength` max: 100 cm

**Comment by adokter** [comment]
Hi @peterdesmet, almost all values can have NaN values, so you loose a lot of the ability to test sanity of the data if you can't discard NaN.

* These can have NaN, so should have no min/max: `u`,`v`,`w`,`ff`,`dd`,`sd_vvp`,`dbz`,`eta`,`dens`,`dbz_all`
* `dbz_all` min: -Inf dBZ
* `dbz_all` max: 1000 dBZ (100 dBZ is possible in theory)
* `rcs` min: can't be actually zero, but anything larger than zero is ok
* `vcp` is an index, see https://en.wikipedia.org/wiki/NEXRAD#Scan_strategies, so no negative values
* `height` min: in theory we could have radars that are positioned below mean sea level
* `radar_height` min: -200 (lowest point on land on earth is -153 metre)
* `radar_wavelength` max: 100
* `radar_wavelength` min: 0.1

**Comment by peterdesmet** [comment]
@adokter thanks, what min/max values would you set for `u`,`v`,`w`,`ff`,`dd`,`sd_vvp`,`dbz`,`eta`,`dens`,`dbz_all` if `NaN` can be ignored?

**Comment by adokter** [comment]
* `u`: [-100,100] m/s
* `v`: [-100,100] m/s
* `w`: number, undefined. We will need https://github.com/adokter/vol2bird/issues/192 prior to setting bounds
* `ff`: [0,100] m/s
* `dd`: [0,360] deg
* `sd_vvp`: [0,100] m/s
* `dbz`: [-Inf, 100]
* `eta`: [0,Inf]
* `dens`: [0,Inf]
* `dbz_all`: [-Inf, 100]

**Comment by peterdesmet** [comment]
@adokter thanks, some final items:

- [x] max `height`: 25000 (let's make it 25km, in case someone wants to explore meteorological profiles (using dbz_all) that in rare cases extend above 10 km)
- [x] max `radar_height`: 9000 (9km)?
- [x] max `dbz_all`: 100
- [x] max `rcs`: Inf. Range is [0,Inf], excluding zero
- [x] max `vcp`: you may want to make this a character or factor, even though US vcps are currently denoted by integer values, because it's a label that refers to a certain scan strategy.
- [x] min `sd_vvp_threshold`: 0
- [x] max `sd_vvp_threshold`: 100

**Comment by peterdesmet** [comment]
Ok, I have set the minimum for `rcs` to `0.01`.

For `vcp` I will use the enum as found on wikipedia: `[12, 212, 112, 215, 121, 31, 32, 35]`

**Comment by adokter** [comment]
Can you make it something very small, like the condition >0. For example for insect studies you might want to set a very small rcs

**Comment by peterdesmet** [comment]
I can’t specify it as >0, so let me know what minimum value you want. 0.001?

**Comment by adokter** [comment]
That is still large for a small insect like an aphid. Could you set it to the float precision, like 2^-10?

**Comment by peterdesmet** [comment]
2^-10 = 0.0009765625 = 0.0001?  The easiest is if I just set more decimals.

**Comment by adokter** [comment]
how many bits are your floats? that is still rather large

**Comment by peterdesmet** [comment]
Not sure, the bits depend on the implementation. 0.0001 would be one square mm.

**Comment by adokter** [comment]
For insects that is still potentially large (the radar size can be much smaller than the physical size of the object). How about 10^(-15), that should still work for a standard 64-bit double
