### ISSUE TITLE
Should a VPTS file always contain all columns, in the defined order?

### ISSUE THREAD

**Issue by peterdesmet** [enram/vpts-dp#31]
All columns: I'm tempted to say no (but label it as RECOMMENDED), because if we decide to add columns, it would make previously produced files invalid. It also blocks software from adding custom columns.

Defined order: I'm tempted to say no (but label it as RECOMMENDED), because if we decide to add columns in the middle, it would make previously produced files invalid

I would REQUIRE files that have a header row, with header names as defined in the format. That should allow any software to merge data.

**Comment by peterdesmet** [comment]
Current requirements:

https://github.com/enram/vpts/blob/d541c825e6a0f02c4c05695802bc03d72db1fd88/pages/format.md?plain=1#L10-L15

**Comment by adokter** [comment]
this looks good to me
