### ISSUE TITLE
Field name alternatives

### ISSUE THREAD

**Issue by peterdesmet** [enram/vpts-dp#32]
I have now added field name alternatives (e.g. `HGHT` for `height`) at https://enram.github.io/vpts/format/, so users can recognize previously used names for fields. These are:

- [ ] height: HGHT
- [ ] height: bin_lower
- [ ] ff: speed
- [ ] dd: direction
- [ ] sd_vvp: rmse
- [ ] dbz_all: DBZH
- [ ] n_dbz_all: nbins
- [ ] eta: linear_eta

@adokter I guess I should not add the following three, as these require a conversion (and are thus not the same):

- [x] dbz: linear_eta
- [x] dens: linear_eta
- [x] dbz_all: linear_eta_unfiltered

**Comment by niconoe** [comment]
Does that mean that the same data can be found under different column names?

I'm not sure how desirable that is (it might be easier to produce files in some cases, but harder to consume them). 

If the sole goal is to make the user recognise them, why not require a single column name, but document the alternative names (for example: require the field to be named `sd_vpp` and add: you might know this data as `rmse`?

**Comment by peterdesmet** [comment]
My intent was more to indicate to the user “also known as” and not provide conversion.

However, it is likely we will need conversion at some point, especially if the standard gets a new version and/or we want to convert legacy data.

**Comment by adokter** [comment]
> @adokter I guess I should not add the following three, as these require a conversion (and are thus not the same):

correct

**Comment by peterdesmet** [comment]
The website well now state the alternative names as `Also known as`, which I hope makes it clearer that it should not be used as a header.

I have also expanded `radar_lat` to `radar_latitude` and `radar_lon` to `radar_longitude`, as I see no point in abbreviating those terms. Let me know if that is ok.
