### ISSUE TITLE
Explicitly describe CSV dialect in documentation

### ISSUE THREAD

**Issue by niconoe** [enram/vpts-dp#33]
Things like:

- Encoding: I strongly suggest UTF-8
- field separator
- line separator (DOS vs Unix)
- quoting (strategy + character used)
- ...

(the list of attributes at https://docs.python.org/3/library/csv.html#dialects-and-formatting-parameters might be a good source of inspirations)

**Comment by peterdesmet** [comment]
I'm very tempted to express what we want using Frictionless CSV dialect terms: https://specs.frictionlessdata.io/csv-dialect/ In effect, we're then creating a Frictionless resource, with a schema and a dialect.

**Comment by niconoe** [comment]
That's fine for me as long as we can easily find those gory-but-important details from the VPTS website: either directly, or by referencing some external specs like a resource description, or an external specifications document (RFC4180, frictionless specs, W3C tabular data standard...).

The only crucial thing about this is to avoid any ambiguity about them (I've had horror stories with DwC-A)

**Comment by bart1** [comment]
I just noticed that definition allows for a comment char by default, note that most R csv readers would always need to set this argument explicitly (and if you do set that by default the value of comments is low as it will always be ignored/not read):
``` r
str<-'asdf\n2\n#2'
textConnection(str) |> read.csv()
#>   asdf
#> 1    2
#> 2   #2
textConnection(str) |> read.csv(comment.char = '#')
#>   asdf
#> 1    2
```

<sup>Created on 2022-05-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by peterdesmet** [comment]
@niconoe Ok, I will include the CSV dialect we want as a spec to the website.

@bart1 as far as I understand, there is no default for `commentChar`. But yes, any non-default value we choose should be translated to the correct parameters. Luckily, I already wrote [read_resource()](https://docs.ropensci.org/frictionless/reference/read_resource.html#csv-dialect) to take care of all that. :-) I'm guessing we don't want to allow comments though?

**Comment by bart1** [comment]
@peterdesmet thanks I maybe understood the frictionless page wrong in a quick skim. I would say no comments, althought it migth be nice sometimes it lacks the infrastructure to do something with it.
ps quick question does the frictionless r package also support reading the units using the units package?

**Comment by peterdesmet** [comment]
> ps quick question does the frictionless r package also support reading the units using the units package?

No. It supports the [Frictionless Specs](https://specs.frictionlessdata.io/), which don't specify units.

**Comment by bart1** [comment]
> No. It supports the [Frictionless Specs](https://specs.frictionlessdata.io/), which don't specify units.

Thanks, good to know

**Comment by peterdesmet** [comment]
@niconoe, the CSV dialect is now added. It does not mention UTF-8 (that is a property of the resource, not dialect in Frictionless). Should I add that as a recommendation?
