### ISSUE TITLE
Name VPTS or VPTS CSV

### ISSUE THREAD

**Issue by peterdesmet** [enram/vpts-dp#36]
Should the format be named VPTS or VPTS CSV (url name `vpts-csv`)? I think I prefer to latter to clarify that this is a text/tabular format and to avoid confusion with the data/class type.

@adokter @CeciliaNilsson709 @niconoe?

**Comment by peterdesmet** [comment]
Note to self, if we choose VPTS CSV, update:

- [x] Repo name to `vpts-csv`
- [x] Schema to `vpts-csv-table-schema.json`
- [x] Titles and references in repo
- [x] Page names in aloftdata
- [x] URLs in aloftdata
- [x] Titles and references in aloftdata repo

**Comment by CeciliaNilsson709** [comment]
VTPS CSV makes more sense to me too, could see how it could get confusing otherwise.

**Comment by niconoe** [comment]
I agree. A bit more verbosity is much better than risking confusin!

**Comment by peterdesmet** [comment]
Thanks, all updated now. Doc page available at https://aloftdata.eu/vpts-csv/
