### ISSUE TITLE
NaN fails min/max constraint

### ISSUE THREAD

**Issue by peterdesmet** [enram/vpts-dp#39]
The string `"NaN"` is used in CSV files to express [undetect](http://adriaandokter.com/bioRad/reference/summary.vp.html#conventions) for columns `u`, `v`, `ff`, `dd`, `sd_vvp`.

- Good: Frictionless validation allows this value for `"type": "number"`
- Bad: Frictionless validation does not allow this value with the `"constraints": { "minimum": -100, "maximum": 100 }`

We could drop the min/max constraints for the fields, but that would be a pity. I therefore suggest to list `"NaN"` as a missing value in the table schema. The result would be:
1. Frictionless validation would skip validation for such values (and thus pass)
2. CSV readers would still read `NaN` into memory as `NaN`, since we don't refer to the table schema for reading data, only for validating data.

/cc @adokter

**Comment by peterdesmet** [comment]
When read as csv, `NaN` will be retained. When read as a data package, `NaN` will be interpreted as missing value.

**Comment by peterdesmet** [comment]
Note that the [standard](https://github.com/enram/aloftdata.eu/blob/b3745dba08f7a17e3fa94ac5358a2f1bd2e1ee80/pages/vpts-csv.md?plain=1#L34) currently mentions that `NaN` should be ignored for constraints, except that it currently isn't ignored (and fails). 😄

**Comment by adokter** [comment]
Listing "NaN" as a missing value in the table schema makes sense to me
