### ISSUE TITLE
Some required fields sometimes have empty data

### ISSUE THREAD

**Issue by peterdesmet** [enram/vpts-dp#40]
We indicated a number of fields in the VPTS format as required (indicated with * in https://aloftdata.eu/vpts-csv/#fields).

Of those fields, @stijnvanhoey noticed that the following sometimes have no data (in the vp files derived from BALTRAD) and thus fail the `required` constraints:

```
ff
dd
sd_vvp
eta
```

@adokter Is it ok that those files then fail validation? Or is it better that those fields are not required?

**Comment by adokter** [comment]
each of these can be `nan` for altitude layers that are never irradiated (typically the lowest and highest altitude layers) - therefore I would make them not required.

**Comment by peterdesmet** [comment]
Thanks for the explanation! @stijnvanhoey did you also encounter `NULL` (rather than `NaN`) values for these properties?
