### ISSUE TITLE
Add source vp as column

### ISSUE THREAD

**Issue by peterdesmet** [enram/vpts-dp#41]
The following 3 files have the same `nominal time` in their metadata:

```
bejab_vp_20230115T000000Z_0x9.h5
bejab_vp_20230115T000500Z_0x9.h5
bejab_vp_20230115T001000Z_0x9.h5
```

Those will end up as rows with duplicate `radar`, `datetime` and `height` in VTPS CSV (that can be filtered by the user). To indicate however where the data were coming from, I propose a new column with the path to the original file, e.g.

```yaml
s3://aloft/baltrad/hdf5/bejab/2023/01/15/bejab_vp_20230115T000000Z_0x9.h5
# or 
s3://noaa-nexrad-level2/2019/10/01/KBGM/KBGM20191001_000542_V06
```

It is basically  the same as the `vp$how$filename_vp` attribute in vp files:

```
/opt/opera/projects/vol2bird_scripts/data/out/bejab_vp_20230115T000000Z_0x9.h5
```

I suggest:

- [ ] To add this as the last column
- [ ] To indicate the full path of the file (on the server it was generated), cf. `filename_vp`. If an S3 bucket, start path as `s3://`
- [ ] To name the column `source_file`.
  - I prefer this over `filename_vp`, which actually contains a path
  - I prefer this over `source`, which we reserve for the data origin, like `baltrad` or `ecog-04003`
- [ ] To make the column optional?
- [ ] To define it as `Path to the source file from which the data were derived.`

@CeciliaNilsson709 @adokter thoughts?

**Comment by peterdesmet** [comment]
Important to note: if vol2bird supports the VPTS CSV as direct output format, then the `source_file` could be a PVOL file, which is a good reason not to name it `vp`-something. In most cases the type of file should be clear from the file name in the path.

**Comment by adokter** [comment]
Hi @peterdesmet, good to mention the source file. We need to decide if we want to mention the polar volume file source, or the vp file source. Both are available as attributes under the `/how` group, `/how/filename_vp` and `/how/filename_pvol`. The polar volume file source is in my opinion the more basic source information.

The decision here also depends on _why_ there are duplicate nominal times. If each file is estimate from a complete polar volume file, the issue is primarily a wrongly defined nominal time (and you may want to update it based on the filename). But it could also be that the underlying polar volume files are incomplete, and that files need to be merged before calculating a profile. In that case the nominal time might be correct, but the resulting profiles are of questionable quality.

**Comment by adokter** [comment]
Suggest using `source_vpfile` and/or `source_pvolfile` as nomenclature, to make clear which source file are referring to

**Comment by peterdesmet** [comment]
In our workflow (on the aloft bucket), the vpfile is the source for the VPTS file, so that is the one I would mention (the pvol is not taken into consideration). We can provide also provide an accessible URL for that source file (i.e. a link to the vp file on the bucket), while that is not the case for the pvol file. If VPTS files are directly produced by vol2bird, the source file _would_ be the pvol file and there it makes sense to mention that one.

All in all I think _either_ the vp or the pvol file would be mentioned as source, not both, and they can be differentiated based on file name, which is why I would only add one field. @adokter does that make sense?

> The decision here also depends on why there are duplicate nominal times. If each file is estimate from a complete polar volume file, the issue is primarily a wrongly defined nominal time (and you may want to update it based on the filename). But it could also be that the underlying polar volume files are incomplete, and that files need to be merged before calculating a profile. In that case the nominal time might be correct, but the resulting profiles are of questionable quality.

We currently don't know for what causes the duplicate nominal times. It might be different for different cases.

**Comment by adokter** [comment]
Hi @peterdesmet, I think it will be important that users can trace back the polar volume file, which contains the actual underlying data for the profile. With your suggested approach they still can of course, by tracking down the vp .h5 file, which will have the /how/filename_pvol attribute in it (but it will be an extra step).

I thought our plan for the future is to migrate to a text output format for vp data as well, which could be similar (identical?) to this new vpts csv format (but containing only a single timestamp) - we will have to make sure that the pvol source remains accessible there. My thinking was that if we want the csv vp format to mirror the csv vpts format we might as well add the pvol source to vpts now, so listing both vp and pvol source.

Another complication: with merged files we can have multiple source files (pvols and scans) to generate a single vp. Could the format allow for a list of source files?

**Comment by peterdesmet** [comment]
> My thinking was that if we want the csv vp format to mirror the csv vpts format we might as well add the pvol source to vpts now, so listing both vp and pvol source.

We definitely want to mirror the VP CSV format to the VPTS CSV format, i.e. they should be the same format (and only differ in the amount of rows). See below the one vs two source column approach, including a suggestion for scans:

## Single source column approach

1. VPTS CSV file created by vptstools from hdf5 vp files (i.e. what runs on the bucket):

radar | datetime | height | source_file
:--- | :--- | :--- | :---
radar 1 | datetime 1 | height 1 | path/to/vp_file1.h5
radar 1 | datetime 1 | height 2 | path/to/vp_file1.h5
radar 1 | datetime 2 | height 1 | path/to/vp_file2.h5
radar 1 | datetime 2 | height 2 | path/to/vp_file2.h5

2. VP(TS) CSV file created by vol2bird from pvol file:

radar | datetime | height | source_file
:--- | :--- | :--- | :---
radar 1 | datetime 1 | height 1 | path/to/pvol_file1.h5
radar 1 | datetime 1 | height 2 | path/to/pvol_file1.h5

3. VP(TS) CSV file created by vol2bird from multiple scans (as comma separated list)

radar | datetime | height | source_file
:--- | :--- | :--- | :---
radar 1 | datetime 1 | height 1 | "path/to/scan_1.h5, path/to/scan_2.h5"
radar 1 | datetime 1 | height 2 | "path/to/scan_1.h5, path/to/scan_2.h5"

4. VPTS CSV file created by concatenating VP CSV files together:

radar | datetime | height | source_file
:--- | :--- | :--- | :---
radar 1 | datetime 1 | height 1 | path/to/pvol_file1.h5
radar 1 | datetime 1 | height 2 | path/to/pvol_file1.h5
radar 1 | datetime 2 | height 1 | path/to/pvol_file2.h5
radar 1 | datetime 2 | height 2 | path/to/pvol_file2.h5

Once could indicate the `vpts1.csv`, `vpts2.csv` in `source_file`, but since concatenating is a lossless process, one might as well retain the pvol file as source file.

## Two source column approach

1. VPTS CSV file created by vptstools from hdf5 vp files (i.e. what runs on the bucket):

radar | datetime | height | source_pvolfile | source_vpfile
:--- | :--- | :--- | :--- | :---
radar 1 | datetime 1 | height 1 | path/to/pvol_file1.h5 | path/to/vp_file1.h5
radar 1 | datetime 1 | height 2 | path/to/pvol_file1.h5 | path/to/vp_file1.h5
radar 1 | datetime 2 | height 1 | path/to/pvol_file1.h5 | path/to/vp_file2.h5
radar 1 | datetime 2 | height 2 | path/to/pvol_file1.h5 | path/to/vp_file2.h5

`source_pvolfile` derived from `/how/filename_pvol`, not because script had access to pvol file

2. VP(TS) CSV file created by vol2bird from pvol file:

radar | datetime | height | source_pvolfile | source_vpfile
:--- | :--- | :--- | :--- | :---
radar 1 | datetime 1 | height 1 | path/to/pvol_file1.h5 | NULL
radar 1 | datetime 1 | height 2 | path/to/pvol_file1.h5 | NULL

3. VP(TS) CSV file created by vol2bird from multiple scans (as comma separated list)

radar | datetime | height | source_pvolfile | source_vpfile
:--- | :--- | :--- | :--- | :---
radar 1 | datetime 1 | height 1 | "path/to/scan_1.h5, path/to/scan_2.h5" | NULL
radar 1 | datetime 1 | height 2 | "path/to/scan_1.h5, path/to/scan_2.h5" | NULL

Note that `source_pvolfile` is a bit misleading, as it contains scans.

4. VPTS CSV file created by concatenating VP CSV files together:

radar | datetime | height | source_pvolfile | source_vpfile
:--- | :--- | :--- | :--- | :---
radar 1 | datetime 1 | height 1 | path/to/pvol_file1.h5 | NULL
radar 1 | datetime 1 | height 2 | path/to/pvol_file1.h5 | NULL
radar 1 | datetime 2 | height 1 | path/to/pvol_file2.h5 | NULL
radar 1 | datetime 2 | height 2 | path/to/pvol_file2.h5 | NULL

Same remark as the single column approach.

---

Personally, I think the single `source_file` column approach is clearer.

**Comment by peterdesmet** [comment]
@adokter replied by email that he is ok with the single column approach.

**Comment by peterdesmet** [comment]
Added in #42
