### ISSUE TITLE
`radar_height` can be a double, rather than integer

### ISSUE THREAD

**Issue by peterdesmet** [enram/vpts-dp#47]
The radar metadata in a h5 file can contain the radar height as a double. This doesn't seem to occur in the BALTRAD data, but in UvA data (provided by DWD), rather height for one radar is 262.4 (see file https://aloftdata.s3-eu-west-1.amazonaws.com/uva/hdf5/dedrs/2017/03/01/dedrs_vp_20170301T0000_10488_v0-3-20.h5):

```R
> library(bioRad)
> vp <- read_vpfiles("~/Downloads/dedrs_vp_20170301T0000_10488_v0-3-20.h5")
> vp
               Vertical profile (class vp)

       radar:  10488 
      source:  WMO:10488 
nominal time:  2017-03-01 00:00:35 
generated by:  vol2bird 0.3.20 
> vp$attributes$where
$height
[1] 262.4

$interval
[1] 200

$lat
[1] 51.12464

$levels
[1] 25

$lon
[1] 13.76864

$maxheight
[1] 5000

$minheight
[1] 0
```

While it can be argued if such precise altitudes can be obtained, I don't think it is invalid. For validation purposes, we should therefore update `radar_height` to a `number`, rather than `integer`:

https://github.com/enram/vpts-csv/blob/4315a558975be88b9d9af0a024497e06a3bc7901/vpts-csv-table-schema.json#L228-L238

@bart1 @CeciliaNilsson709 @adokter thoughts?

**Comment by peterdesmet** [comment]
Alternatively, processing to vpts could force it to be an integer.

**Comment by peterdesmet** [comment]
As part of the processing of the BALTRAD archive @PietrH will correct those values (cast to integer) before writing to VPTS-CSV. Nothing needs to be updated in the standard.

**I don't know if this is a useful check/feature for bioRad needs to have?**

**Comment by bart1** [comment]
Quick comment while catching up after holidays without knowing the details, did you look at the opera ODIM standard what it specifies it seems good to follow that as that is where it will be mostly derived from.

**Comment by PietrH** [comment]
I didn't, I never considered a mismatch between VPTS-CSV and ODIM. 

Do you happen to have a link to the ODIM documentation?

**Comment by bart1** [comment]
As far as I know 2.4 is the newest: https://www.eumetnet.eu/wp-content/uploads/2021/07/ODIM_H5_v2.4.pdf on page 12 (18 of the document) it defines it as a double
