### ISSUE TITLE
NEXRAD vpts csv format for cajun (UMass Amherst)

### ISSUE THREAD

**Issue by adokter** [enram/vpts-dp#5]
Here an example for the KLOT radar in cajun csv format: [KLOT20070301_231800.csv](https://github.com/enram/vpts/files/6142690/KLOT20070301_231800.txt)

At this point each file contains a single vp (so that's a lot of files). These might get aggregated into longer daily or monthly files.

Here is indicated how (several of the) vol2bird and cajun header names match:
https://github.com/adokter/bioRad/blob/33ec6ed50f64029b7cc097b819aa1c9afa0587d4/R/read_cajun.R#L38-L45

**Comment by adokter** [comment]
Description of correspondence between vol2bird and cajun data columns:

| vol2bird | cajun |
|--- | --- |
| date |  **date (suggested)** |
| time |  **time (suggested)** |
| HGHT | bin_lower |
| u | u |
| v | v |
| w |  |
| ff | speed |
| dd | direction |
| sd_vvp | rmse |
| gap | |
| dbz | _maps to linear_eta_ |
| eta | linear_eta |
| dens | _maps to linear_eta under certain assumptions_ |
| DBZH | _maps to linear_eta_unfiltered_ |
| n | |
| n_dbz | |
| n_all | |
| n_dbz_all | nbins |
|  | height |
|  | elev1 |
|  | nvolumes_gr35_e1 |
|  | elev2 |
|  | nvolumes_gr35_e2 |
| _given in header_ | vcp |
| _maps to DBZH_ | linear_eta_unfiltered |
| | percent_rain |

**Comment by adokter** [comment]
Here an example vol2bird current csv format:
[KBGM20190706_024302_V06.txt](https://github.com/enram/vpts/files/6166348/KBGM20190706_024302_V06.txt)

**Comment by peterdesmet** [comment]
Most of the above fields are now covered in the VPTS flat table format #25. The ones that are not are:

- [ ] height (except if this is `radar_height`)
- [ ] elev1
- [ ] nvolumes_gr35_e1
- [ ] elev2
- [ ] nvolumes_gr35_e2
- [ ] percent_rain
- [x] linear_eta_unfiltered

Should any of these be included in VPTS?

**Comment by adokter** [comment]
linear_eta_unfiltered should not get lost, it's related to bioRad's `DBZH`/`dbz_all` and is related to it via a transformation that depends on the wavelength (see https://adriaandokter.com/bioRad/reference/eta_to_dbz.html)

**Comment by peterdesmet** [comment]
So do you want to add it as a separate field? If so, how should it be named and at what position should it be included? https://enram.github.io/vpts/format/

**Comment by adokter** [comment]
Isn't it problematic to have a duplicate field (apart from a log transformation)? We can also convert the linear_eta_unfiltered field to dbz_all prior to storing it as a vpts csv file.

**Comment by peterdesmet** [comment]
> We can also convert the linear_eta_unfiltered field to dbz_all prior to storing it as a vpts csv file.

That seems reasonable, no extra field for this then. @adokter none of the other fields mentioned in https://github.com/enram/vpts/issues/5#issuecomment-1119391348 should be included?

**Comment by adokter** [comment]
No, but it would be good if the standard allows for these optional fields to be included. But I don't think they need to be documented and defined explicitly at this point
