### ISSUE TITLE
Do we guarantee a row order in CSV file

### ISSUE THREAD

**Issue by niconoe** [enram/vpts-dp#8]
Similar files I've worked with for the CROW project where sorted by time, then altitude.

Is this something we want to enforce in the standard or not?

Enforcing it means a tiny bit more complexity on the "producer" side, but life a bit easier on the "consumer" side.

Opinion: I'd be tempted to say yes:
- because files are probably more often read than generated 
- might be nicer for end-users, especially for less technical people (when having a manual glance at the file)

**Comment by peterdesmet** [comment]
I'm also tempted to say yes, but curious how it scales. Probably fairly well, since even a vpts file for a whole year is not going to be big data.

**Comment by niconoe** [comment]
I was also wondering about the scale, this also depends on what we decide for #9.

But that consideration pushes me further on the "yes" side, because I prefer a slow/memory hungry generator (often run asynchronously, on a large server) than a slow memory/hungry consumer (often run on a personal laptop - BioRAD for example or sometimes in a web browser - CROW)

**Comment by peterdesmet** [comment]
Agree, so let’s enforce a row order by timestamp and then height

**Comment by niconoe** [comment]
Perfect Peter, since we (at this step) need clear decisions rather than perfect ones, Iet's settle this.

I'll update the specs document.
