### ISSUE TITLE
Does the standard enforce limits on the temporal range

### ISSUE THREAD

**Issue by niconoe** [enram/vpts-dp#9]
So far, I've worked with files that were covering exactly one day of data.

Do we want to guarantee anything on that aspect (always one day? maximum one year? minimum two different timestamps?...)

Opinion:

I'd be tempted to say no. (obviously, I want a clearly expressed temporal range in the metadata, but that is already planned - see example JSON file)

**Comment by peterdesmet** [comment]
Indeed, there is no theoretical limit on the time span.

**Comment by niconoe** [comment]
Thanks, noted.
